FISHING_ROD__TOP = 1315
FISHING_ROD__HEIGHT = 70
FISHING_ROD__LEFT = 925
FISHING_ROD__WIDTH = 70

AQUARIUM_BAR__TOP = 675
AQUARIUM_BAR__HEIGHT = 700
AQUARIUM_BAR__LEFT = 2230
AQUARIUM_BAR__WIDTH = 50

AQUARIUM__TOP = 710
AQUARIUM__HEIGHT = 100
AQUARIUM__LEFT = 300
AQUARIUM__WIDTH = 1975

FISHING_ROD_PATHS = [
    "data\\launched_fishing_rod.png",
    "data\\unlaunched_fishing_rod.png",
]

AQUARIUM_PATH = "data\\aquarium.png"

TMP_AQUARIUM_PATH = "screenshots\\aquarium_screenshot.png"
