FISHING_ROD__TOP = 1320
FISHING_ROD__HEIGHT = 70
FISHING_ROD__LEFT = 3165
FISHING_ROD__WIDTH = 70

AQUARIUM_BAR__TOP = 850
AQUARIUM_BAR__HEIGHT = 547
AQUARIUM_BAR__LEFT = 4465
AQUARIUM_BAR__WIDTH = 15

AQUARIUM__TOP = 895
AQUARIUM__HEIGHT = 100
AQUARIUM__LEFT = 2540
AQUARIUM__WIDTH = 1975

FISHING_ROD_PATHS = [
    "data\\launched_fishing_rod1080.png",
    "data\\unlaunched_fishing_rod1080.png",
]

AQUARIUM_PATH = "data\\aquarium1080.png"

TMP_AQUARIUM_PATH = "screenshots\\aquarium_screenshot.png"
